# Generated by Django 4.2.13 on 2024-08-04 21:32

from django.db import migrations, models
import miapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_calificacion_asignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=miapp.models.obtener_ruta_subida),
        ),
    ]
